// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CurrentUserController from "./current_user_controller"
application.register("current-user", CurrentUserController)

import NotesTableController from "./notes_table_controller"
application.register("notes-table", NotesTableController)
