require:
  - rubocop-rspec

# All

AllCops:
  NewCops: enable
  Exclude:
    - 'test/test_helper.rb'
    - 'db/schema.rb'
    - 'config/**/**'
    - '**/db/migrate/*'
    - '**/Gemfile.lock'
    - '**/Rakefile'
    - '**/rails'
    - '**/vendor/**/*'
    - '**/spec_helper.rb'
    - 'node_modules/**/*'
    - 'bin/*'

# Disabled

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/Rails/InferredSpecType:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: false

# Adjusted

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/channels/application_cable/connection_test.rb'

Layout/LineLength:
  Max: 150
