development:
  host: localhost
  port: 6379
  db: 1

test:
  host: localhost
  port: 6379
  db: 0

production:
  url: <%= ENV['REDIS_URL'] %>
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
  db: 1
